<h1>Weather for ${cityName}</h1>
<p><b>Id station:</b> ${cityID}</p>
<p><b>Date of measurement:</b> ${cityDate}</p>
<p><b>Time of measurement:</b> ${cityHour}:00</p>
<p><b>Temperature: </b>${cityTemperature} &#x2103</p>
<p><b>Wind speed: </b>${cityWindSpeed} m/s</p>
<p><b>Wind direction: </b>${windDirection}</p>
<p><b>Pressure: </b>${pressure}</p>
<p><b>Relative humidity: </b>${humidity}</p>
<p><b>Total rainfall: </b>${totalRainfall}</p>