<h1>Weather for ${cityName}</h1>
<p><b>Id station:</b> ${cityID?c}</p>
<p><b>Date of measurement:</b> ${cityDate}</p>
<p><b>Time of measurement:</b> ${cityHour}</p>
<p><b>Temperature: </b>${cityTemperature} &#x2103</p>
<p><b>Wind speed: </b>${cityWindSpeed?c} m/s</p>
<p><b>Wind direction: </b>${windDirection}</p>
<p><b>Pressure: </b>${pressure?c}</p>
<p><b>Relative humidity: </b>${humidity}</p>
<p><b>Total Rainfall: </b>${totalRainfall}</p>